import os
# os.system("your command")
print("1")
# os.system("cd /d S:\\網通部\\◎資訊\\test\\")
# print("2")
# os.system("git init")
# print("3")
# os.system("git add .")
# print("4")
# os.system("git commit -m 'New file'")
# print("5")
# os.system("git push")
# print("6")
# os.chdir("S:\\網通部\\◎資訊\\test\\")
# print(os.system("echo %CD%"))
print("1")
os.system("UpdateGithub.exe")
# os.system("cd /d S:\\網通部\\◎資訊\\test\\")
# print("2")
# os.system("git init")
# print("3")
# os.system("git add stock.jpg")
# print("4")
# os.system("git commit -m \\'New file")
# print("5")
# os.system("git push")
# print("6")
# os.system("S:\\網通部\\◎資訊\\test\\upload.bat")
print(os.system("echo %CD%"))