DELIMITER ;;

DROP FUNCTION IF EXISTS getColumnNameWithIndex;
CREATE FUNCTION getColumnNameWithIndex(TableName VARCHAR(255),IndexName 

VARCHAR(255),SeqInIndex VARCHAR(255))
RETURNS VARCHAR(255)
BEGIN
	DECLARE ColName VARCHAR(255);
	SELECT
	    COLUMN_NAME into ColName
	FROM
	    INFORMATION_SCHEMA.STATISTICS
	where 
	    TABLE_NAME = TableName and INDEX_NAME = IndexName and SEQ_IN_INDEX 

= SeqInIndex;
	RETURN ColName;
END;

;;

DELIMITER ;